name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repository
      - name: Checkout code
        uses: actions/checkout@v3

    # install node environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

    # install dependencies
      - name: Install dependencies
        run: npm ci

    #run tests
      - name: Run tests
        run: npm test
        env:
          PORT: 3001   

   # build docker image
      - name: Build Docker image
        run: docker build -t the-pipe .

   # trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-pipe'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

   # deploy 
      - name: Deployment step
        run: echo "Deploy step handled by render auto-deploy"
