name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # download repository
      - name: Checkout code
        uses: actions/checkout@v3

    # install node environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

    # install dependencies
      - name: Install dependencies
        run: npm install
      
    #run tests
      - name: Run tests
        run: npm test
        env:
          PORT: 3001   

   # build docker image
      - name: Build Docker image
        run: docker build -t the-pipe:${{ github.sha }} .

   # list of images
      - name: images list
        run: docker images

   # test docker images     
      - name: Test Docker image runs
        run: |
          docker run -d --name test-container the-pipe:${{ github.sha }}
          sleep 5
          docker ps
          docker logs test-container
          docker stop test-container

    # run health check
      - name: Health check
        run: |
         docker run -d -p 3001:3001 --name app the-pipe:${{ github.sha }}
         sleep 10
         curl -f http://localhost:3001/health || exit 0   

   # trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'the-pipe'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

   # deploy 
      - name: Deployment step
        run: echo "Deploy step handled by render auto-deploy"
